#ifndef SOUND_CONFIG_H_
#define SOUND_CONFIG_H_

#define CONTROLLER_CONNECTED 1

#define GEN_SND_START 1
#define GEN_SND_END 25

#define CHAT_SND_START 26
#define CHAT_SND_END 44

#define HAPPY_SND_START 51
#define HAPPY_SND_END 59

#define SAD_SND_START 75
#define SAD_SND_END 80

#define HUM_SND_START 130
#define HUM_SND_END 156

#define LEIA_SND_START 161
#define LEIA_SND_END 165

#define SCREAM_SND_START 126
#define SCREAM_SND_END 129

#define PROC_SND_START 240
#define PROC_SND_END 245

#define WHISTLE_SND_START 101
#define WHISTLE_SND_END 104

#define AUTO_SND_START 1
#define AUTO_SND_END 50

#define SW_SND_THEME 190
#define EMPIRE_SND_THEME 192
#define CANTINA_SND_THEME 191
#define SW_CHORUS_THEME 193

#define MUS_THRILLER 203
#define RANDOM_MUS_START 179
#define RANDOM_MUS_END 187

#define HOLIDAY_MUS_START 350
#define HOLIDAY_MUS_END 352

#define R2THEME_MUS_START 176
#define R2THEME_MUS_END 179

#define DOODOO_SND 49
#define OVERHERE_SND 50
#define PATROL_SND 48
#define ANNOYED_SND 75

#define IMPERIAL_SIREN 400

#define BG_MUS_START 255
#endif // #ifndef SOUND_CONFIG_H_
